### ISSUE TITLE
print issue?

### ISSUE THREAD

**Issue by uzulim** [P-Edwards/tdasampling#1]
I tried running tdasampling and there was a syntax error from the `print` function.

In particular, there was error from
`print "\n The algorithm instance checking bounds: ", space.global_bounds,"has boxes remaining: ", len(space.bad_boxes), "\n"`

Was the code written in Python2? Maybe it should be modified to fit Python3's `print` usage. I'm currently directly modifying the code.

**Comment by P-Edwards** [comment]
Hi Finn- thanks for pointing this out. Yes, tdasampling is written for Python 2.7. I will update the packaging requirements to reflect this. The shebangs for the terminal scripts are written to call python2 as well.

In the mean time, most systems that have python installed also have python2 installed under the global terminal call `python2` and similarly have pip for your python2 installation under `pip2`. Those should work for tdasampling.
